### ISSUE TITLE
There is no password input dialogue

### ISSUE THREAD

**Issue by nielsk** [barskern/plymouth-theme-simple-image#1]
When use full-disk encryption there is no password input dialogue shown. You can input your password but nothing is displayed.

**Comment by barskern** [comment]
As far as I know [`plymouth`](https://wiki.archlinux.org/index.php/Plymouth) has nothing to do with password input. It only enables you to display a splash screen on boot up. Hence if you have trouble with password input you should rather debug your [display manager](https://wiki.archlinux.org/index.php/Display_manager).

**Comment by nielsk** [comment]
I have to investigate it further what one has to do for this. But the LUKS-password prompt has to come before the machine booted. With other themes I get a password prompt in the plymouth screen for my LUKS-password (and then a second one when the login-screen of my display manager appears).

**Comment by nielsk** [comment]
This is it:

> Plymouth.SetDisplayPasswordFunction: the callback function is called when the display should display a password dialogue. First arg is prompt string, the second is the number of bullets. 
https://www.freedesktop.org/wiki/Software/Plymouth/Scripts/

**Comment by barskern** [comment]
Ah okay I didn't know about that feature. However adding support for it is outside the scope of this package. The point of this package is to just be a "simple-image". Feel free to fork this project to implement it. :smile:
